services:
  # front
  frontend:
    build:
      context: ./Frontend/techyourjob-frontend/
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${PORT_FRONT}:3000"
    volumes:
      - ./Frontend/techyourjob-frontend:/app
    env_file:
      - .env

  # db
  db:
    image: postgis/postgis:15-3.3
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris
    ports:
      - "${PORT_DB}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./Backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  # logiciel indien
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PORT_PGADMIN}:80"
    depends_on:
      - db

  # service de mise a jour de la db avec du scrap
  scheduler:
    build: ./Data/Get_Data_API
    container_name: scheduler

  # mise à jour des données du dashboard toutes les 15min
  dashboard_scheduler:
    build: ./Data/Dashboard
    container_name: dashboard_scheduler
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT_DB=${PORT_DB}
    volumes:
      - ./Frontend/techyourjob-frontend/public/data/cache:/usr/local/app/../../Frontend/techyourjob-frontend/public/data/cache
    env_file:
      - .env

  # backend
  backend:
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    container_name: backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PORT_BACK=${PORT_BACK}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - LOGODEV_KEY=${LOGODEV_KEY}
      - PORT_MINIO=${PORT_MINIO}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - FRONTEND_URL=${FRONTEND_URL}
      - MAIL_SENDER=${MAIL_SENDER}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "${PORT_BACK}:5000"
    volumes:
      - ./Backend:/usr/local/app
      - /usr/local/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "${PORT_MINIO}:9000"
      - "9001:9001" # pgadmin version onligne
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

  minio-init:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};
      mc mb --ignore-existing local/candidatures;
      mc mb --ignore-existing local/documents;
      "

  ia:
    build:
      context: ./IA/
      dockerfile: Dockerfile
    container_name: ia
    ports:
      - "${PORT_IA}:8000"

volumes:
  minio_data:
