const express = require("express");
const router = express.Router();

const registerRoutes = require("./register");
const loginRoutes = require("./login");
const logoutRoutes = require("./logout");
const get_userRoutes = require("./get_user");
const put_userGlobalRoutes = require("./put_userGlobal");
const put_userProfilRoutes = require("./put_userProfil");
const userImagesRoutes = require("./user_images");
const put_userExperienceRoutes = require("./put_userExperience");
const put_userFormationRoutes = require("./put_userFormation");
const grouped_postsRoutes = require("./grouped_posts");
const logoRoutes = require("./logo");
const postRoutes = require("./post");
const forgot_passwordRoutes = require("./forgotpassword");
const get_info_test = require("./Features_unique/Get_Infos_Test");
const upload_candidature = require("./Features_unique/Upload_fichier");
const Get_fichier_candidat = require("./Features_unique/Get_Candidats_test");
const Start_Docker = require("./Features_unique/Start_Docker");
const enterpriseIDRoutes = require("./enterpriseID");
const enterpriseXRoutes = require("./enterpriseX");
const enterpriseTopXRoutes = require("./enterpriseTopX");
const searchPostsRoutes = require("./searchPosts");
const deleteUserRoutes = require("./admin/delete_user");
const deleteEnterpriseRoutes = require("./admin/delete_enterprise");
const deletePostRoutes = require("./admin/delete_post");
const updatePrivilegeRoutes = require("./admin/update_privilege");
const getTopSalaryRoutes = require("./data/get_topSalary");
const SearchUser = require("./admin/rechercher_user");
const SearchEntreprise = require("./admin/rechercher_entreprise");
const SearchPOste = require("./admin/rechercher_poste");
const See_Other_Account = require("./See_Account");
const refreshRoutes = require("./refresh");
const ia = require("./ia");
const ProfilstatsRoutes = require("./data/Profilstats");
const Add_test_technique = require("./Features_unique/Add_test_technique");

router.use("/", ia);
router.use("/", registerRoutes);
router.use("/", loginRoutes);
router.use("/", logoutRoutes);
router.use("/", get_userRoutes);
router.use("/", put_userGlobalRoutes);
router.use("/", put_userProfilRoutes);
router.use("/", userImagesRoutes);
router.use("/", put_userExperienceRoutes);
router.use("/", put_userFormationRoutes);
router.use("/", grouped_postsRoutes);
router.use("/", logoRoutes);
router.use("/", postRoutes);
router.use("/", forgot_passwordRoutes);
router.use("/", get_info_test);
router.use("/", upload_candidature);
router.use("/", Get_fichier_candidat);
router.use("/api", Start_Docker);
router.use("/", enterpriseIDRoutes);
router.use("/", enterpriseXRoutes);
router.use("/", enterpriseTopXRoutes);
router.use("/", searchPostsRoutes);
router.use("/", deleteUserRoutes);
router.use("/", deleteEnterpriseRoutes);
router.use("/", deletePostRoutes);
router.use("/", updatePrivilegeRoutes);
router.use("/dashboard", getTopSalaryRoutes);
router.use("/", SearchUser);
router.use("/", SearchEntreprise);
router.use("/", See_Other_Account);
router.use("/", SearchPOste);
router.use("/", ProfilstatsRoutes);
router.use("/", refreshRoutes);
router.use("/", Add_test_technique);

module.exports = router;
